content: 
  command: pet
  probability: 30
  antialias: true
  disabled: []
  commandHead: ''
  respondSelfNudge: false
  respondReply: true
  cachePoolSize: 10000
  keyListFormat: FORWARD
  disablePolicy: FULL
  disabledGroups: []
  fuzzy: false
  strictCommand: true
  synchronized: false
  gifEncoder: BUFFERED_STREAM
  gifMaxSize: []
  headless: true
  autoUpdate: true
  updateIgnore: []
  repositoryUrl: 'https://dituon.github.io/petpet'