content: 
  version: 3.0
  command: pet
  probability: 30
  antialias: true
  disabled: 
    - Avatar.NONE
  keyCommand: false
  commandMustAt: true
  respondImage: false
  respondSelfNudge: false
  headless: false