content: 
  version: 3.4
  command: pet
  probability: 30
  antialias: true
  disabled: 
    - Avatar.NONE
  keyCommand: false
  commandMustAt: false
  respondImage: true
  respondSelfNudge: false
  headless: false