content: 
  command: pet
  probability: 30
  antialias: true
  disabled: []
  commandHead: ''
  respondSelfNudge: false
  respondReply: true
  cachePoolSize: 10000
  keyListFormat: FORWARD
  disablePolicy: FULL
  disabledGroups: []
  fuzzy: false
  strictCommand: true
  synchronized: false
  gifEncoder: ANIMATED_LIB
  gifMaxSize: 
    - 200
    - 200
    - 32
  headless: true
  autoUpdate: true
  repositoryUrl: 'https://raw.githubusercontent.com/Dituon/petpet/main'
  devMode: false